name: Publish Package to Registry
on: [ push ]

jobs:
  lint-package:
    name: Lint the source code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - run: npm ci
        name: Install dependencies
      - run: npm run lint
        name: Lint the source code

  build-package:
    name: Build the package
    runs-on: ubuntu-latest

    needs:
      - lint-package

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build the package

  publish-package:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Publish the package to the github package registry
    runs-on: ubuntu-latest
    needs:
      - lint-package
      - build-package

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
        name: Install dependencies
      - run: |
          echo "@username:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm publish
        name: Publish package to registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
