name: Publish Package to Registry
on: [ push ]

jobs:
  build-package:
    name: Build the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build the package


  publish-package:
    name: Publish the package to the github package registry
    runs-on: ubuntu-latest
    needs:
      - build-package

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
        name: Install dependencies
      - run: |
          echo "@username:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm publish
        name: Publish package to registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
